"""
AI-assisted Source Code Auditing Tool.

This module provides SAST (Static Application Security Testing) capabilities
by leveraging the LLM's understanding of source code. It can be used to audit
raw source code files provided by the user, or automatically run on decompiled
pseudo-C code generated by Ghidra.
"""

from __future__ import annotations

import os
import re
from typing import Any

from fastmcp import Context

from reversecore_mcp.core.decorators import log_execution
from reversecore_mcp.core.error_handling import handle_tool_errors
from reversecore_mcp.core.logging_config import get_logger
from reversecore_mcp.core.metrics import track_metrics
from reversecore_mcp.core.plugin import Plugin
from reversecore_mcp.core.result import ToolResult, failure, success
from reversecore_mcp.core.sast.python_ast_scanner import PythonASTScanner
from reversecore_mcp.core.sast.regex_scanner import RegexScanner
from reversecore_mcp.core.sast.rule_manager import rule_manager
from reversecore_mcp.core.security import validate_file_path
from reversecore_mcp.core.validators import validate_tool_parameters

logger = get_logger(__name__)


@log_execution(tool_name="audit_source_code")
@track_metrics("audit_source_code")
@handle_tool_errors
async def audit_source_code(
    file_path: str,
    language: str | None = None,
    ctx: Context | None = None,
) -> ToolResult:
    """
    Perform a security audit on a source code file (SAST).

    This tool analyzes source code (C, C++, Python, Go, etc.) to identify
    potential security vulnerabilities such as buffer overflows, injection flaws,
    and weak cryptography. It provides a structured breakdown of dangerous patterns
    found in the code to guide deeper manual or AI-driven analysis.

    Use this tool when you have access to original source code or when you
    want to analyze decompiled output exported to a file.

    Args:
        file_path: Path to the source code file.
        language: Optional language hint (e.g., 'c', 'python'). If None, inferred from extension.

    Returns:
        ToolResult containing the source code (or truncated version) and identified risks.
    """
    validate_tool_parameters("audit_source_code", {"file_path": file_path})
    validated_path = validate_file_path(file_path)

    # 1. Check file size
    try:
        file_size = os.path.getsize(validated_path)
        if file_size > 5_000_000:  # 5MB limit for source code
            return failure(
                "FILE_TOO_LARGE",
                f"Source file size ({file_size} bytes) exceeds 5MB limit for auditing.",
                hint="Consider auditing specific components or using a dedicated SAST tool.",
            )
    except OSError as e:
        return failure("FILE_ERROR", f"Could not read file: {e}")

    # 2. Read source code
    try:
        with open(validated_path, encoding="utf-8", errors="replace") as f:
            source_code = f.read()
    except Exception as e:
        return failure("READ_ERROR", f"Failed to read source code: {e}")

    # 3. Infer language if not provided
    if not language:
        ext = os.path.splitext(validated_path)[1].lower()
        lang_map = {
            ".c": "c",
            ".cpp": "cpp",
            ".h": "c",
            ".hpp": "cpp",
            ".py": "python",
            ".go": "go",
            ".js": "javascript",
            ".java": "java",
            ".rs": "rust",
        }
        language = lang_map.get(ext, "unknown")

    # 4. Perform AST or Regex scan based on language
    rules = rule_manager.get_rules_for_language(language)
    scan_findings = []

    if language == "python":
        # Try AST first, fallback to regex if syntax error
        scan_findings = PythonASTScanner().scan(source_code, rules)
        if not scan_findings:
            scan_findings = RegexScanner().scan(source_code, rules)
    else:
        scan_findings = RegexScanner().scan(source_code, rules)

    if language in {"c", "cpp"}:
        scan_findings.extend(_scan_c_index_bounds(source_code))

    # 5. Format findings into Category -> list[str] structure for backward compatibility
    static_findings: dict[str, list[str]] = {}
    for finding in scan_findings:
        cat = finding["category"]
        severity = finding["severity"].upper()
        rule_id = finding["rule_id"]
        msg = finding["message"]
        line = finding["line"]
        code_str = finding["code"]

        finding_str = f"Line {line}: {code_str} | [🚨 {severity}] {rule_id}: {msg}"
        if cat not in static_findings:
            static_findings[cat] = []
        static_findings[cat].append(finding_str)

    # 6. Prepare output (truncate if too long for context window, but keep findings)
    max_lines = 2000
    lines = source_code.split("\n")
    is_truncated = len(lines) > max_lines

    if is_truncated:
        display_code = (
            "\n".join(lines[:max_lines]) + f"\n\n... [Truncated {len(lines) - max_lines} lines] ..."
        )
    else:
        display_code = source_code

    return success(
        display_code,
        format="source_code",
        language=language,
        static_findings=static_findings,
        is_truncated=is_truncated,
        description=f"Source code loaded for auditing. {sum(len(v) for v in static_findings.values())} risky patterns identified.",
    )


class SourceAuditorPlugin(Plugin):
    """Plugin for Source Code Auditing (SAST)."""

    name = "source_auditor"
    description = "Provides tools for analyzing source code vulnerabilities."

    def register(self, mcp_server: Any) -> None:
        """Register the audit_source_code tool."""
        mcp_server.tool()(audit_source_code)


def _scan_c_index_bounds(source_code: str) -> list[dict[str, Any]]:
    """Find C array indexes with incomplete bounds checks inside a function."""
    findings: list[dict[str, Any]] = []
    lines = source_code.splitlines()

    for function in _iter_c_functions(lines):
        guard_state = _collect_index_guards(function["lines"])
        for rel_line, code in enumerate(function["lines"], start=1):
            line_number = function["start_line"] + rel_line - 1
            for access in _iter_array_accesses(code):
                index = access["index"]
                guards = guard_state.get(index, {"lower": False, "upper": False})

                if guards["upper"] and not guards["lower"]:
                    findings.append(
                        {
                            "category": "Bounds Check",
                            "severity": "high",
                            "rule_id": "RCMCP-SAST-C-012",
                            "message": (
                                f"Array index '{index}' is used after an upper-bound check, "
                                "but no lower-bound check was found in the same function. "
                                "Negative values can bypass upper-only validation and cause "
                                "out-of-bounds memory access."
                            ),
                            "line": line_number,
                            "code": code.strip(),
                        }
                    )
                elif not guards["upper"] and not guards["lower"]:
                    findings.append(
                        {
                            "category": "Bounds Check",
                            "severity": "medium",
                            "rule_id": "RCMCP-SAST-C-013",
                            "message": (
                                f"Array index '{index}' is used without an obvious same-function "
                                "bounds check."
                            ),
                            "line": line_number,
                            "code": code.strip(),
                        }
                    )

    return findings


def _iter_c_functions(lines: list[str]) -> list[dict[str, Any]]:
    """Return approximate C function bodies with 1-based start lines."""
    functions: list[dict[str, Any]] = []
    signature = ""
    start_line = 1
    brace_depth = 0
    body: list[str] = []
    in_function = False

    for line_number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not in_function:
            signature = f"{signature} {stripped}".strip()
            if "{" not in stripped:
                continue
            if not _looks_like_function_signature(signature):
                signature = ""
                continue

            in_function = True
            start_line = line_number
            brace_depth = stripped.count("{") - stripped.count("}")
            body = [line]
            signature = ""
            if brace_depth <= 0:
                functions.append({"start_line": start_line, "lines": body})
                in_function = False
            continue

        body.append(line)
        brace_depth += stripped.count("{") - stripped.count("}")
        if brace_depth <= 0:
            functions.append({"start_line": start_line, "lines": body})
            in_function = False
            body = []

    return functions


def _looks_like_function_signature(signature: str) -> bool:
    """Best-effort filter for C function definitions."""
    if not re.search(r"\w+\s*\([^;]*\)\s*\{", signature):
        return False
    control_prefixes = ("if", "for", "while", "switch", "do", "else")
    return not signature.lstrip().startswith(control_prefixes)


def _collect_index_guards(function_lines: list[str]) -> dict[str, dict[str, bool]]:
    """Collect lower/upper guard hints from if conditions in a function."""
    guards: dict[str, dict[str, bool]] = {}
    condition_pattern = re.compile(r"\bif\s*\((?P<condition>.*)\)")
    for_pattern = re.compile(r"\bfor\s*\((?P<init>[^;]*);(?P<condition>[^;]*);(?P<update>[^)]*)\)")
    lower_patterns = [
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*<\s*0\b"),
        re.compile(r"\b0\s*<=\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*>=\s*0\b"),
        re.compile(r"\b0\s*>\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*0\b"),
    ]
    upper_patterns = [
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*>\s*[A-Za-z_][A-Za-z0-9_]*\b"),
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*>=\s*[A-Za-z_][A-Za-z0-9_]*\b"),
        re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\s*<\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
        re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\s*<=\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
    ]

    for line in function_lines:
        guard_expressions = []
        if_match = condition_pattern.search(line)
        if if_match:
            guard_expressions.append(if_match.group("condition"))

        for_match = for_pattern.search(line)
        if for_match:
            guard_expressions.append(for_match.group("init"))
            guard_expressions.append(for_match.group("condition"))

        for expression in guard_expressions:
            for pattern in lower_patterns:
                for guard_match in pattern.finditer(expression):
                    _mark_guard(guards, guard_match.group("idx"), "lower")
            for pattern in upper_patterns:
                for guard_match in pattern.finditer(expression):
                    index = guard_match.group("idx")
                    if index != "0":
                        _mark_guard(guards, index, "upper")

    return guards


def _mark_guard(guards: dict[str, dict[str, bool]], index: str, guard_type: str) -> None:
    guards.setdefault(index, {"lower": False, "upper": False})[guard_type] = True


def _iter_array_accesses(line: str) -> list[dict[str, str]]:
    """Find array access expressions using identifier indexes."""
    if line.lstrip().startswith(("#", "typedef", "struct", "enum")):
        return []

    access_pattern = re.compile(
        r"(?P<array>(?:[A-Za-z_][A-Za-z0-9_]*|[A-Za-z_][A-Za-z0-9_]*->"
        r"[A-Za-z_][A-Za-z0-9_]*|[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*))"
        r"\s*\[\s*(?P<index>[A-Za-z_][A-Za-z0-9_]*)\s*\]"
    )
    return [
        {"array": match.group("array"), "index": match.group("index")}
        for match in access_pattern.finditer(line)
    ]
