"""
AI-assisted Source Code Auditing Tool.

This module provides SAST (Static Application Security Testing) capabilities
by leveraging the LLM's understanding of source code. It can be used to audit
raw source code files provided by the user, or automatically run on decompiled
pseudo-C code generated by Ghidra.
"""

from __future__ import annotations

import os
from typing import Any

from fastmcp import Context

from reversecore_mcp.core.decorators import log_execution
from reversecore_mcp.core.error_handling import handle_tool_errors
from reversecore_mcp.core.logging_config import get_logger
from reversecore_mcp.core.metrics import track_metrics
from reversecore_mcp.core.plugin import Plugin
from reversecore_mcp.core.result import ToolResult, failure, success
from reversecore_mcp.core.security import validate_file_path
from reversecore_mcp.core.validators import validate_tool_parameters

logger = get_logger(__name__)

# Basic heuristics for fast static detection before deep AI review
_DANGEROUS_PATTERNS = {
    "C/C++ Memory": ["strcpy", "sprintf", "gets", "strcat", "memcpy", "malloc"],
    "Command Injection": ["system", "popen", "exec", "os.system", "subprocess"],
    "Format String": ["printf", "fprintf", "syslog"],
    "Cryptographic": ["MD5", "SHA1", "DES", "RC4", "srand", "rand"],
}


def _fast_static_scan(code: str) -> dict[str, list[str]]:
    """Perform a fast heuristic scan to highlight areas of interest for the AI."""
    findings: dict[str, list[str]] = {category: [] for category in _DANGEROUS_PATTERNS}

    for line_idx, line in enumerate(code.split("\n"), start=1):
        for category, patterns in _DANGEROUS_PATTERNS.items():
            for pattern in patterns:
                # Simple exact word boundary match
                import re

                if re.search(r"\b" + re.escape(pattern) + r"\b", line):
                    findings[category].append(f"Line {line_idx}: {line.strip()}")
                    break  # Found one pattern from this category on this line

    # Filter out empty categories
    return {k: v for k, v in findings.items() if v}


@log_execution(tool_name="audit_source_code")
@track_metrics("audit_source_code")
@handle_tool_errors
async def audit_source_code(
    file_path: str,
    language: str | None = None,
    ctx: Context | None = None,
) -> ToolResult:
    """
    Perform a security audit on a source code file (SAST).

    This tool analyzes source code (C, C++, Python, Go, etc.) to identify
    potential security vulnerabilities such as buffer overflows, injection flaws,
    and weak cryptography. It provides a structured breakdown of dangerous patterns
    found in the code to guide deeper manual or AI-driven analysis.

    Use this tool when you have access to original source code or when you
    want to analyze decompiled output exported to a file.

    Args:
        file_path: Path to the source code file.
        language: Optional language hint (e.g., 'c', 'python'). If None, inferred from extension.

    Returns:
        ToolResult containing the source code (or truncated version) and identified risks.
    """
    validate_tool_parameters("audit_source_code", {"file_path": file_path})
    validated_path = validate_file_path(file_path)

    # 1. Check file size
    try:
        file_size = os.path.getsize(validated_path)
        if file_size > 5_000_000:  # 5MB limit for source code
            return failure(
                "FILE_TOO_LARGE",
                f"Source file size ({file_size} bytes) exceeds 5MB limit for auditing.",
                hint="Consider auditing specific components or using a dedicated SAST tool.",
            )
    except OSError as e:
        return failure("FILE_ERROR", f"Could not read file: {e}")

    # 2. Read source code
    try:
        with open(validated_path, encoding="utf-8", errors="replace") as f:
            source_code = f.read()
    except Exception as e:
        return failure("READ_ERROR", f"Failed to read source code: {e}")

    # 3. Infer language if not provided
    if not language:
        ext = os.path.splitext(validated_path)[1].lower()
        lang_map = {
            ".c": "c",
            ".cpp": "cpp",
            ".h": "c",
            ".hpp": "cpp",
            ".py": "python",
            ".go": "go",
            ".js": "javascript",
            ".java": "java",
            ".rs": "rust",
        }
        language = lang_map.get(ext, "unknown")

    # 4. Perform fast static scan
    static_findings = _fast_static_scan(source_code)

    # 5. Prepare output (truncate if too long for context window, but keep findings)
    max_lines = 2000
    lines = source_code.split("\n")
    is_truncated = len(lines) > max_lines

    if is_truncated:
        display_code = (
            "\n".join(lines[:max_lines]) + f"\n\n... [Truncated {len(lines) - max_lines} lines] ..."
        )
    else:
        display_code = source_code

    return success(
        display_code,
        format="source_code",
        language=language,
        static_findings=static_findings,
        is_truncated=is_truncated,
        description=f"Source code loaded for auditing. {sum(len(v) for v in static_findings.values())} risky patterns identified.",
    )


class SourceAuditorPlugin(Plugin):
    """Plugin for Source Code Auditing (SAST)."""

    name = "source_auditor"
    description = "Provides tools for analyzing source code vulnerabilities."

    def register(self, mcp_server: Any) -> None:
        """Register the audit_source_code tool."""
        mcp_server.tool()(audit_source_code)
