"""
AI-assisted Source Code Auditing Tool.

This module provides SAST (Static Application Security Testing) capabilities
by leveraging the LLM's understanding of source code. It can be used to audit
raw source code files provided by the user, or automatically run on decompiled
pseudo-C code generated by Ghidra.
"""

from __future__ import annotations

import os
import re
from typing import Any

from fastmcp import Context

from reversecore_mcp.core.decorators import log_execution
from reversecore_mcp.core.error_handling import handle_tool_errors
from reversecore_mcp.core.logging_config import get_logger
from reversecore_mcp.core.metrics import track_metrics
from reversecore_mcp.core.plugin import Plugin
from reversecore_mcp.core.result import ToolResult, failure, success
from reversecore_mcp.core.sast.python_ast_scanner import PythonASTScanner
from reversecore_mcp.core.sast.regex_scanner import RegexScanner
from reversecore_mcp.core.sast.rule_manager import rule_manager
from reversecore_mcp.core.security import validate_file_path
from reversecore_mcp.core.validators import validate_tool_parameters

logger = get_logger(__name__)


@log_execution(tool_name="audit_source_code")
@track_metrics("audit_source_code")
@handle_tool_errors
async def audit_source_code(
    file_path: str,
    language: str | None = None,
    ctx: Context | None = None,
) -> ToolResult:
    """
    Perform a security audit on a source code file (SAST).

    This tool analyzes source code (C, C++, Python, Go, etc.) to identify
    potential security vulnerabilities such as buffer overflows, injection flaws,
    and weak cryptography. It provides a structured breakdown of dangerous patterns
    found in the code to guide deeper manual or AI-driven analysis.

    Use this tool when you have access to original source code or when you
    want to analyze decompiled output exported to a file.

    Args:
        file_path: Path to the source code file.
        language: Optional language hint (e.g., 'c', 'python'). If None, inferred from extension.

    Returns:
        ToolResult containing the source code (or truncated version) and identified risks.
    """
    validate_tool_parameters("audit_source_code", {"file_path": file_path})
    validated_path = validate_file_path(file_path)

    # 1. Check file size
    try:
        file_size = os.path.getsize(validated_path)
        if file_size > 5_000_000:  # 5MB limit for source code
            return failure(
                "FILE_TOO_LARGE",
                f"Source file size ({file_size} bytes) exceeds 5MB limit for auditing.",
                hint="Consider auditing specific components or using a dedicated SAST tool.",
            )
    except OSError as e:
        return failure("FILE_ERROR", f"Could not read file: {e}")

    # 2. Read source code
    try:
        with open(validated_path, encoding="utf-8", errors="replace") as f:
            source_code = f.read()
    except Exception as e:
        return failure("READ_ERROR", f"Failed to read source code: {e}")

    # 3. Infer language if not provided
    if not language:
        ext = os.path.splitext(validated_path)[1].lower()
        lang_map = {
            ".c": "c",
            ".cpp": "cpp",
            ".h": "c",
            ".hpp": "cpp",
            ".py": "python",
            ".go": "go",
            ".js": "javascript",
            ".java": "java",
            ".rs": "rust",
        }
        language = lang_map.get(ext, "unknown")

    # 4. Perform AST or Regex scan based on language
    rules = rule_manager.get_rules_for_language(language)
    scan_findings = []

    if language == "python":
        # Try AST first, fallback to regex if syntax error
        scan_findings = PythonASTScanner().scan(source_code, rules)
        if not scan_findings:
            scan_findings = RegexScanner().scan(source_code, rules)
    else:
        scan_findings = RegexScanner().scan(source_code, rules)

    if language in {"c", "cpp"}:
        scan_findings.extend(_scan_c_index_bounds(source_code))
        scan_findings.extend(_scan_c_stalled_loops(source_code))
        scan_findings.extend(_scan_c_use_after_free(source_code))
        scan_findings.extend(_scan_c_cleanup_call_graph(source_code))
        scan_findings.extend(_scan_c_unchecked_pointer_dereference(source_code))
        scan_findings.extend(_scan_c_redirect_credential_leak(source_code))

    # 5. Format findings into Category -> list[str] structure for backward compatibility
    static_findings: dict[str, list[str]] = {}
    for finding in scan_findings:
        cat = finding["category"]
        severity = finding["severity"].upper()
        rule_id = finding["rule_id"]
        msg = finding["message"]
        line = finding["line"]
        code_str = finding["code"]

        finding_str = f"Line {line}: {code_str} | [🚨 {severity}] {rule_id}: {msg}"
        if cat not in static_findings:
            static_findings[cat] = []
        static_findings[cat].append(finding_str)

    structured_findings = _build_structured_findings(scan_findings, str(validated_path), language)

    # 6. Prepare output (truncate if too long for context window, but keep findings)
    max_lines = 2000
    lines = source_code.split("\n")
    is_truncated = len(lines) > max_lines

    if is_truncated:
        display_code = (
            "\n".join(lines[:max_lines]) + f"\n\n... [Truncated {len(lines) - max_lines} lines] ..."
        )
    else:
        display_code = source_code

    return success(
        display_code,
        format="source_code",
        language=language,
        static_findings=static_findings,
        structured_findings=structured_findings,
        is_truncated=is_truncated,
        description=f"Source code loaded for auditing. {sum(len(v) for v in static_findings.values())} risky patterns identified.",
    )


class SourceAuditorPlugin(Plugin):
    """Plugin for Source Code Auditing (SAST)."""

    name = "source_auditor"
    description = "Provides tools for analyzing source code vulnerabilities."

    def register(self, mcp_server: Any) -> None:
        """Register the audit_source_code tool."""
        mcp_server.tool()(audit_source_code)


def _scan_c_index_bounds(source_code: str) -> list[dict[str, Any]]:
    """Find C array indexes with incomplete bounds checks inside a function."""
    findings: list[dict[str, Any]] = []
    lines = source_code.splitlines()

    for function in _iter_c_functions(lines):
        guard_state = _collect_index_guards(function["lines"])
        for rel_line, code in enumerate(function["lines"], start=1):
            line_number = function["start_line"] + rel_line - 1
            for access in _iter_array_accesses(code):
                index = access["index"]
                guards = guard_state.get(index, {"lower": False, "upper": False})

                if guards["upper"] and not guards["lower"]:
                    findings.append(
                        {
                            "category": "Bounds Check",
                            "severity": "high",
                            "rule_id": "RCMCP-SAST-C-012",
                            "function": function["name"],
                            "message": (
                                f"Array index '{index}' is used after an upper-bound check, "
                                "but no lower-bound check was found in the same function. "
                                "Negative values can bypass upper-only validation and cause "
                                "out-of-bounds memory access."
                            ),
                            "line": line_number,
                            "code": code.strip(),
                            "evidence_type": "static",
                            "vulnerability_class": "out_of_bounds_access",
                            "sink": access["array"],
                            "index": index,
                            "guard_status": {
                                "has_lower_bound": guards["lower"],
                                "has_upper_bound": guards["upper"],
                            },
                            "confidence": "high",
                            "verification_status": "candidate",
                            "next_validation_steps": [
                                "Trace whether the index is attacker-controlled.",
                                "Compare patched code for an added lower-bound check.",
                                "Run sanitizer build with boundary and wrapped numeric inputs.",
                            ],
                        }
                    )
                elif not guards["upper"] and not guards["lower"]:
                    findings.append(
                        {
                            "category": "Bounds Check",
                            "severity": "medium",
                            "rule_id": "RCMCP-SAST-C-013",
                            "function": function["name"],
                            "message": (
                                f"Array index '{index}' is used without an obvious same-function "
                                "bounds check."
                            ),
                            "line": line_number,
                            "code": code.strip(),
                            "evidence_type": "static",
                            "vulnerability_class": "out_of_bounds_access",
                            "sink": access["array"],
                            "index": index,
                            "guard_status": {
                                "has_lower_bound": guards["lower"],
                                "has_upper_bound": guards["upper"],
                            },
                            "confidence": "medium",
                            "verification_status": "needs_triage",
                            "next_validation_steps": [
                                "Check whether bounds are guaranteed by caller or loop structure.",
                                "Trace whether the index is attacker-controlled.",
                            ],
                        }
                    )

    return findings


def _scan_c_stalled_loops(source_code: str) -> list[dict[str, Any]]:
    """Find bounded-size while loops whose condition state is never updated."""
    findings: list[dict[str, Any]] = []
    lines = source_code.splitlines()
    condition_re = re.compile(r"\bwhile\s*\((?P<condition>[^)]*)\)")
    identifier_re = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\b")

    for line_no, line in enumerate(lines, start=1):
        match = condition_re.search(line)
        if not match:
            continue
        condition = match.group("condition")
        identifiers = {
            token
            for token in identifier_re.findall(condition)
            if token not in {"true", "false", "NULL"}
        }
        if not identifiers:
            continue

        body: list[str] = []
        depth = line.count("{") - line.count("}")
        for body_line in lines[line_no : line_no + 25]:
            body.append(body_line)
            depth += body_line.count("{") - body_line.count("}")
            if depth <= 0:
                break
        body_text = "\n".join(body)
        if "break" in body_text or "goto" in body_text:
            continue
        updated = any(
            re.search(rf"\b{re.escape(name)}\s*(?:\+\+|--|[+\-*/]?=)", body_text)
            for name in identifiers
        )
        if not updated and depth <= 0:
            findings.append(
                {
                    "category": "Infinite Loop",
                    "severity": "high",
                    "rule_id": "RCMCP-SAST-C-014",
                    "message": "While-loop condition variables are not updated in the loop body; attacker-controlled input may cause non-termination.",
                    "line": line_no,
                    "code": line.strip(),
                    "evidence_type": "static",
                    "vulnerability_class": "infinite_loop",
                    "confidence": "medium",
                    "verification_status": "candidate",
                    "next_validation_steps": [
                        "Trace whether the loop condition depends on attacker-controlled state.",
                        "Run with a timeout and collect a stack trace for non-termination.",
                        "Compare patched code for a progress check, iteration bound, or exit condition.",
                    ],
                }
            )
    return findings


def _scan_c_use_after_free(source_code: str) -> list[dict[str, Any]]:
    """Find direct pointer dereferences after free within one function body."""
    findings: list[dict[str, Any]] = []
    lines = source_code.splitlines()
    for function in _iter_c_functions(lines):
        freed: dict[str, int] = {}
        for rel_line, code in enumerate(function["lines"], start=1):
            line_no = function["start_line"] + rel_line - 1
            for pointer in re.findall(r"\bfree\s*\(\s*([A-Za-z_]\w*)\s*\)", code):
                freed[pointer] = line_no
            for pointer, free_line in list(freed.items()):
                if line_no <= free_line or re.search(
                    rf"\b{re.escape(pointer)}\s*(?:->|\[)|\*\s*{re.escape(pointer)}\b", code
                ):
                    findings.append(
                        {
                            "category": "Use After Free",
                            "severity": "high",
                            "rule_id": "RCMCP-SAST-C-015",
                            "message": f"Pointer '{pointer}' is dereferenced after being freed on line {free_line}.",
                            "line": line_no,
                            "code": code.strip(),
                            "evidence_type": "static",
                            "vulnerability_class": "use_after_free",
                            "confidence": "high",
                            "verification_status": "candidate",
                            "next_validation_steps": [
                                "Confirm the pointer aliases the allocation released at the free site.",
                                "Run AddressSanitizer with an input reaching both statements.",
                                "Check whether ownership is transferred or the pointer is reset before use.",
                            ],
                        }
                    )
                    freed.pop(pointer)
    return findings


def _scan_c_cleanup_call_graph(source_code: str) -> list[dict[str, Any]]:
    """Find free-containing cleanup functions reused without nulling ownership."""
    lines = source_code.splitlines()
    functions = _iter_c_functions(lines)
    function_names = {f["name"] for f in functions}
    findings: list[dict[str, Any]] = []
    for function in functions:
        body = "\n".join(function["lines"])
        if "free(" not in body.replace(" ", "") or re.search(
            r"\b[A-Za-z_]\w*(?:->|\.)[A-Za-z_]\w*\s*=\s*NULL\b", body
        ):
            continue
        call_count = (
            sum(
                len(re.findall(rf"\b{re.escape(function['name'])}\s*\(", line))
                for line in lines
                if function["name"] in function_names
            )
            - 1
        )  # exclude the function definition itself
        if call_count < 2:
            continue
        free_line = next(
            function["start_line"] + i
            for i, line in enumerate(function["lines"])
            if re.search(r"\bfree\s*\(", line)
        )
        findings.append(
            {
                "category": "Double Free",
                "severity": "high",
                "rule_id": "RCMCP-SAST-C-016",
                "message": f"Cleanup function '{function['name']}' frees memory and is called {call_count} times without an obvious ownership reset.",
                "line": free_line,
                "code": function["lines"][free_line - function["start_line"]].strip(),
                "evidence_type": "static",
                "vulnerability_class": "double_free",
                "confidence": "medium",
                "verification_status": "candidate",
                "next_validation_steps": [
                    "Trace whether both call sites can operate on the same allocation.",
                    "Run AddressSanitizer through each cleanup path.",
                    "Set the owner pointer to NULL after free or make cleanup idempotent.",
                ],
            }
        )
    return findings


def _scan_c_unchecked_pointer_dereference(source_code: str) -> list[dict[str, Any]]:
    """Find local pointer field dereferences without a same-function null guard."""
    findings: list[dict[str, Any]] = []
    for function in _iter_c_functions(source_code.splitlines()):
        body = function["lines"]
        pointer_names = set(
            re.findall(r"\b[A-Za-z_]\w*\s*\*\s*([A-Za-z_]\w*)\s*=", "\n".join(body))
        )
        guarded = {
            name
            for name in pointer_names
            if re.search(rf"\b(?:if\s*\([^)]*|assert\s*\()\b{re.escape(name)}\b", "\n".join(body))
        }
        reported: set[str] = set()
        for rel_line, code in enumerate(body, start=1):
            for name in pointer_names - guarded:
                if name in reported:
                    continue
                if re.search(rf"\b{re.escape(name)}\s*->\s*[A-Za-z_]", code):
                    line_no = function["start_line"] + rel_line - 1
                    findings.append(
                        {
                            "category": "Null Pointer / Type Safety",
                            "severity": "medium",
                            "rule_id": "RCMCP-SAST-C-017",
                            "message": f"Pointer '{name}' is dereferenced without an obvious same-function null guard.",
                            "line": line_no,
                            "code": code.strip(),
                            "evidence_type": "static",
                            "vulnerability_class": "null_pointer_dereference",
                            "confidence": "medium",
                            "verification_status": "needs_triage",
                            "next_validation_steps": [
                                "Trace whether deserialization or error paths can leave the pointer uninitialized.",
                                "Run UBSan/ASan with NULL and partial-initialization inputs.",
                                "Confirm the owning object establishes the field before cleanup.",
                            ],
                        }
                    )
                    reported.add(name)
                    break
    return findings


def _scan_c_redirect_credential_leak(source_code: str) -> list[dict[str, Any]]:
    """Find cookie/auth header propagation without an obvious host check."""
    findings: list[dict[str, Any]] = []
    for function in _iter_c_functions(source_code.splitlines()):
        body = function["lines"]
        text = "\n".join(body)
        has_credential_state = "cookieheader" in text.lower() or "authorization" in text.lower()
        has_redirect_context = "redirect" in text.lower() or "new host" in text.lower()
        has_host_check = any(
            re.search(r"\b(host|hostname|origin)\b", line, re.IGNORECASE)
            and re.search(r"==|!=|strcmp|strcasecmp|same", line, re.IGNORECASE)
            for line in body
        )
        if not (has_redirect_context and has_credential_state) or has_host_check:
            continue
        rel_line = next(
            (
                i
                for i, line in enumerate(body, start=1)
                if "cookieheader" in line.lower() or "authorization" in line.lower()
            ),
            1,
        )
        findings.append(
            {
                "category": "Information Disclosure",
                "severity": "high",
                "rule_id": "RCMCP-SAST-C-018",
                "function": function["name"],
                "message": "Cookie or authorization state is propagated in redirect-related code without an obvious same-host check.",
                "line": function["start_line"] + rel_line - 1,
                "code": body[rel_line - 1].strip(),
                "evidence_type": "static",
                "vulnerability_class": "sensitive_information_disclosure",
                "sink": "redirect credential/header propagation",
                "confidence": "medium",
                "verification_status": "candidate",
                "next_validation_steps": [
                    "Trace whether the redirect destination can differ from the original host.",
                    "Run a two-host redirect harness and capture destination request headers.",
                    "Compare patched code for same-origin filtering or credential stripping.",
                ],
            }
        )
    return findings


def _iter_c_functions(lines: list[str]) -> list[dict[str, Any]]:
    """Return approximate C function bodies with 1-based start lines."""
    functions: list[dict[str, Any]] = []
    signature = ""
    start_line = 1
    brace_depth = 0
    body: list[str] = []
    in_function = False

    for line_number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not in_function:
            # Skip comments and preprocessor lines outside functions
            if stripped.startswith(("#", "//", "/*", "*")):
                continue
            signature = f"{signature} {stripped}".strip()
            # If declaration/statement ended without an open brace, reset signature
            if ";" in stripped and "{" not in stripped:
                signature = ""
                continue
            if "{" not in stripped:
                # Prevent runaway signature accumulator
                if len(signature) > 1000:
                    signature = signature[-500:]
                continue
            if not _looks_like_function_signature(signature):
                signature = ""
                continue

            in_function = True
            start_line = line_number
            brace_depth = stripped.count("{") - stripped.count("}")
            name = _extract_c_function_name(signature)
            body = [line]
            signature = ""
            if brace_depth <= 0:
                functions.append({"start_line": start_line, "name": name, "lines": body})
                in_function = False
            continue

        body.append(line)
        brace_depth += stripped.count("{") - stripped.count("}")
        if brace_depth <= 0:
            functions.append({"start_line": start_line, "name": name, "lines": body})
            in_function = False
            body = []

    return functions


def _looks_like_function_signature(signature: str) -> bool:
    """Best-effort filter for C function definitions."""
    if not re.search(r"\w+\s*\([^;]*\)\s*\{", signature):
        return False
    control_prefixes = ("if", "for", "while", "switch", "do", "else")
    return not signature.lstrip().startswith(control_prefixes)


def _extract_c_function_name(signature: str) -> str:
    """Extract a best-effort C function name from a definition signature."""
    match = re.search(r"([A-Za-z_][A-Za-z0-9_]*)\s*\([^;]*\)\s*\{", signature)
    return match.group(1) if match else "unknown"


def _collect_index_guards(function_lines: list[str]) -> dict[str, dict[str, bool]]:
    """Collect lower/upper guard hints from if conditions in a function."""
    guards: dict[str, dict[str, bool]] = {}
    condition_pattern = re.compile(r"\bif\s*\((?P<condition>.*)\)")
    for_pattern = re.compile(r"\bfor\s*\((?P<init>[^;]*);(?P<condition>[^;]*);(?P<update>[^)]*)\)")
    lower_patterns = [
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*<\s*0\b"),
        re.compile(r"\b0\s*<=\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*>=\s*0\b"),
        re.compile(r"\b0\s*>\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*==\s*0\b"),
        re.compile(r"\b0\s*==\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*<=\s*0\b"),
        re.compile(r"\b0\s*>=\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
    ]
    upper_patterns = [
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*>\s*[A-Za-z_][A-Za-z0-9_]*\b"),
        re.compile(r"\b(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\s*>=\s*[A-Za-z_][A-Za-z0-9_]*\b"),
        re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\s*<\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
        re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\s*<=\s*(?P<idx>[A-Za-z_][A-Za-z0-9_]*)\b"),
    ]

    for line in function_lines:
        guard_expressions = []
        if_match = condition_pattern.search(line)
        if if_match:
            guard_expressions.append(if_match.group("condition"))

        for_match = for_pattern.search(line)
        if for_match:
            guard_expressions.append(for_match.group("init"))
            guard_expressions.append(for_match.group("condition"))

        for expression in guard_expressions:
            for pattern in lower_patterns:
                for guard_match in pattern.finditer(expression):
                    _mark_guard(guards, guard_match.group("idx"), "lower")
            for pattern in upper_patterns:
                for guard_match in pattern.finditer(expression):
                    index = guard_match.group("idx")
                    if index != "0":
                        _mark_guard(guards, index, "upper")

    return guards


def _mark_guard(guards: dict[str, dict[str, bool]], index: str, guard_type: str) -> None:
    guards.setdefault(index, {"lower": False, "upper": False})[guard_type] = True


def _iter_array_accesses(line: str) -> list[dict[str, str]]:
    """Find array access expressions using identifier indexes."""
    if line.lstrip().startswith(("#", "typedef", "struct", "enum")):
        return []

    access_pattern = re.compile(
        r"(?P<array>(?:[A-Za-z_][A-Za-z0-9_]*|[A-Za-z_][A-Za-z0-9_]*->"
        r"[A-Za-z_][A-Za-z0-9_]*|[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*))"
        r"\s*\[\s*(?P<index>[A-Za-z_][A-Za-z0-9_]*)\s*\]"
    )
    return [
        {"array": match.group("array"), "index": match.group("index")}
        for match in access_pattern.finditer(line)
    ]


def _build_structured_findings(
    scan_findings: list[dict[str, Any]], file_path: str, language: str
) -> list[dict[str, Any]]:
    """Normalize SAST findings for downstream evidence merging."""
    structured = []
    for finding in scan_findings:
        next_steps = finding.get("next_validation_steps")
        if not next_steps:
            next_steps = _default_validation_steps(finding)
        item = {
            "source": "audit_source_code",
            "evidence_type": finding.get("evidence_type", "static"),
            "rule_id": finding.get("rule_id"),
            "category": finding.get("category"),
            "severity": finding.get("severity"),
            "confidence": finding.get(
                "confidence", _confidence_from_severity(finding.get("severity"))
            ),
            "verification_status": finding.get("verification_status", "needs_triage"),
            "file_path": file_path,
            "language": language,
            "line": finding.get("line"),
            "function": finding.get("function"),
            "code": finding.get("code"),
            "message": finding.get("message"),
            "vulnerability_class": finding.get("vulnerability_class"),
            "sink": finding.get("sink"),
            "index": finding.get("index"),
            "guard_status": finding.get("guard_status"),
            "next_validation_steps": next_steps,
        }
        structured.append({key: value for key, value in item.items() if value is not None})
    return structured


def _default_validation_steps(finding: dict[str, Any]) -> list[str]:
    """Provide actionable next steps when a rule did not supply any."""
    category = str(finding.get("category", "")).lower()
    if "buffer" in category or "memcpy" in str(finding.get("message", "")).lower():
        return [
            "Trace the size expression to its source and compare it with the destination capacity.",
            "Compile with AddressSanitizer and UndefinedBehaviorSanitizer.",
            "Create a boundary-sized input and confirm whether the sink writes past the allocation.",
        ]
    if "integer" in category or "overflow" in category:
        return [
            "Check arithmetic for signedness, truncation, and maximum-value overflow.",
            "Exercise boundary values under UBSan with integer-overflow checks enabled.",
        ]
    return [
        "Trace the finding to a controllable input and validate it with a focused sanitizer test."
    ]


def _confidence_from_severity(severity: str | None) -> str:
    """Map legacy SAST severity to evidence confidence."""
    if severity == "high":
        return "high"
    if severity == "medium":
        return "medium"
    return "low"
