"""Testcase Minimizer and Standalone PoC Generator."""

from __future__ import annotations

import os
import subprocess
import tempfile
from pathlib import Path

from reversecore_mcp.core.logging_config import get_logger
from reversecore_mcp.core.r2_helpers import calculate_dynamic_timeout
from reversecore_mcp.core.result import ToolResult, failure, success
from reversecore_mcp.core.security import validate_file_path

logger = get_logger(__name__)


def generate_python_poc_script(
    target_binary_path: str,
    payload_bytes: bytes,
    cwe_id: str = "CWE-122",
    bug_name: str = "Heap Buffer Overflow",
) -> str:
    """Generate a clean, standalone Python reproduction script for CVE submission.

    Args:
        target_binary_path: Path or command name of target binary.
        payload_bytes: Minimal crash-inducing payload bytes.
        cwe_id: CWE vulnerability identifier.
        bug_name: Human-readable vulnerability name.

    Returns:
        Complete Python script string.
    """
    hex_payload = payload_bytes.hex()

    script = f'''#!/usr/bin/env python3
"""
CVE Proof-of-Concept Reproduction Script
Vulnerability: {bug_name} ({cwe_id})
Target: {target_binary_path}
Generated by: Reversecore_MCP AI CVE Hunter Engine
"""

import subprocess
import sys
import tempfile
from pathlib import Path

PAYLOAD_HEX = "{hex_payload}"
PAYLOAD = bytes.fromhex(PAYLOAD_HEX)

def reproduce():
    print(f"[*] Triggering PoC against target: {target_binary_path}")
    print(f"[*] Payload size: {{len(PAYLOAD)}} bytes")

    with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as f:
        f.write(PAYLOAD)
        tmp_poc = f.name

    try:
        cmd = ["{target_binary_path}", tmp_poc]
        print(f"[*] Executing command: {{' '.join(cmd)}}")
        proc = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=10,
        )
        print(f"[*] Process exited with return code: {{proc.returncode}}")
        if proc.stderr:
            print("[*] Stderr output:")
            print(proc.stderr.decode("utf-8", errors="ignore"))
    except subprocess.TimeoutExpired:
        print("[!] Execution timed out (possible hang or loop)")
    except Exception as e:
        print(f"[!] Execution failed: {{e}}")
    finally:
        try:
            Path(tmp_poc).unlink(missing_ok=True)
        except Exception:
            pass

if __name__ == "__main__":
    reproduce()
'''
    return script


def generate_c_poc_harness(
    target_function: str,
    payload_bytes: bytes,
    cwe_id: str = "CWE-122",
) -> str:
    """Generate a standalone C reproducer file for vendor bug reporting.

    Args:
        target_function: Target parser function name.
        payload_bytes: Raw payload byte content.
        cwe_id: CWE identifier.

    Returns:
        C source code reproducing the crash.
    """
    byte_array_str = ", ".join(f"0x{b:02x}" for b in payload_bytes[:512])

    c_code = f"""/*
 * Standalone C Reproduction Harness for {cwe_id}
 * Generated by Reversecore_MCP
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

// Forward declaration of target entry point
extern int {target_function}(const uint8_t *data, size_t size);

static const uint8_t g_poc_payload[] = {{
    {byte_array_str}
}};
static const size_t g_poc_size = {len(payload_bytes)};

int main(int argc, char **argv) {{
    printf("[*] Running PoC testcase against {target_function} (Size: %zu bytes)\\n", g_poc_size);
    {target_function}(g_poc_payload, g_poc_size);
    printf("[*] Finished execution.\\n");
    return 0;
}}
"""
    return c_code


def _test_input_causes_crash(binary_path: Path, data: bytes, timeout: int = 5) -> bool:
    """Check if feeding data to target binary triggers a crash (non-zero or signal)."""
    with tempfile.NamedTemporaryFile(suffix=".bin", delete=False) as tmp:
        tmp.write(data)
        tmp_name = tmp.name

    try:
        res = subprocess.run(
            [str(binary_path), tmp_name],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            timeout=timeout,
        )
        # Non-zero returncode or ASan ERROR indication in stderr
        is_crash = res.returncode != 0 or b"AddressSanitizer" in res.stderr
        return is_crash
    except (subprocess.TimeoutExpired, OSError):
        return False
    finally:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass


def delta_debug_minimize(
    binary_path: Path,
    original_bytes: bytes,
    max_iterations: int = 50,
) -> bytes:
    """Delta-debugging algorithm to shrink crash input to the minimal byte payload.

    Args:
        binary_path: Path to target executable.
        original_bytes: Crash-inducing payload.
        max_iterations: Maximum bisection iterations.

    Returns:
        Minimized byte payload.
    """
    if len(original_bytes) <= 4:
        return original_bytes

    current = bytearray(original_bytes)
    chunk_size = len(current) // 2

    iteration = 0
    while chunk_size > 0 and iteration < max_iterations:
        iteration += 1
        reduced = False
        i = 0
        while i < len(current):
            # Try removing chunk [i : i + chunk_size]
            candidate = current[:i] + current[i + chunk_size :]
            if len(candidate) > 0 and _test_input_causes_crash(binary_path, bytes(candidate)):
                current = candidate
                reduced = True
                break
            i += chunk_size

        if not reduced:
            chunk_size //= 2

    return bytes(current)


async def minimize_poc_impl(
    binary_path: str,
    crash_input_path: str,
    target_function: str | None = None,
    timeout: int | None = None,
) -> ToolResult:
    """Minimize crash testcase input and generate standalone PoCs.

    Args:
        binary_path: Path to target binary in workspace.
        crash_input_path: Path to crash-inducing input file.
        target_function: Optional target parser function name.
        timeout: Maximum execution timeout in seconds.

    Returns:
        ToolResult with minimized payload, size reduction percentage, and PoC scripts.
    """
    try:
        bin_path = validate_file_path(binary_path)
        input_path = validate_file_path(crash_input_path)
    except Exception as e:
        return failure("INVALID_PATH", f"Validation error: {e}")

    if not bin_path.exists() or not input_path.exists():
        return failure("FILE_NOT_FOUND", "Target binary or crash input file does not exist.")

    calc_timeout = calculate_dynamic_timeout(bin_path, base_timeout=timeout or 30)

    original_payload = input_path.read_bytes()
    original_size = len(original_payload)

    # Perform minimization
    try:
        minimized_payload = delta_debug_minimize(
            bin_path, original_payload, max_iterations=min(calc_timeout, 30)
        )
    except Exception as e:
        logger.warning(f"Delta-debug minimization fallback: {e}")
        minimized_payload = original_payload

    minimized_size = len(minimized_payload)
    reduction_pct = (
        round(((original_size - minimized_size) / original_size) * 100, 1)
        if original_size > 0
        else 0.0
    )

    # Generate Python and C PoCs
    func_name = target_function or "parse_input"
    py_poc = generate_python_poc_script(
        target_binary_path=str(bin_path),
        payload_bytes=minimized_payload,
    )
    c_poc = generate_c_poc_harness(
        target_function=func_name,
        payload_bytes=minimized_payload,
    )
    gdb_cmd = (
        f"gdb -q {bin_path} -ex 'r {crash_input_path}' -ex 'bt' -ex 'info registers' -ex 'quit'"
    )

    result_data = {
        "binary_path": str(bin_path),
        "original_input_size_bytes": original_size,
        "minimized_input_size_bytes": minimized_size,
        "reduction_percentage": f"{reduction_pct}%",
        "minimized_payload_hex": minimized_payload[:256].hex(),
        "standalone_python_poc": py_poc,
        "standalone_c_poc": c_poc,
        "gdb_reproduction_command": gdb_cmd,
        "summary": f"Minimized PoC from {original_size}B to {minimized_size}B ({reduction_pct}% reduction). Standalone Python and C reproducers generated.",
    }

    return success(result_data)
